var field_keys = {
    "BSM": "标识码",
    "YSDM": "要素代码",
    "DKBM": "地块编码",
    "DKMC": "地块名称",
    "SYQXZ": "所有权性质",
    "DKLB": "地块类别",
    "TDLYLX": "土地利用类型",
    "DLDJ": "地力等级",
    "TDYT": "土地用途",
    "SFJBNT": "是否基本农田",
    "SCMJ": "实测面积(平方米)",
    "DKDZ": "地块东至",
    "DKXZ": "地块西至",
    "DKNZ": "地块南至",
    "DKBZ": "地块北至",
    "DKBZXX": "地块备注信息",
    "ZJRXM": "指界人姓名",
    "DCRQ": "调查日期",
    "DCY": "调查员",
    "DCJS": "调查记事",
    "SHRQ": "审核日期",
    "SHY": "审核员",
    "SHJS": "审核记事",
    "TFH": "图幅号",
    "KJZB": "空间坐标",
    "CBFMC": "承包方(代表)名称",
    "DKZT": "地块状态",
    "FBFBM": "发包方编码",
    "FBFMC":"发包方名称",
    "CBFDBXM": "承包方代表姓名",
    "FBFFZRXM": "发包方负责人姓名",

    "LZZT": "流转状态",

    "XZQDM": "行政区代码",
    "CBQXQ": "承包期限",
    "CBQXZ": "承包期限"
    ,"CBFBM":"承包方编码"
}